apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartmuseum
  template:
    metadata:
      name: charmuseum-pod
      labels:
        app: chartmuseum
    spec:
      containers:
      - name: chartmuseum
        image: chartmuseum/chartmuseum:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          privileged: true
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1"
            memory: "1G"
          limits:
            cpu: "1"
            memory: "1G"
        env:
        - name: STORAGE
          value: "local"
        - name: STORAGE_LOCAL_ROOTDIR
          value: "/charts"
        - name: AUTH_ANONYMOUS_GET
          value: "1"
        - name: BASIC_AUTH_USER
          value: "admin"
        - name: BASIC_AUTH_PASS
          value: "admin"
        volumeMounts:
        - name: chartmuseum-mnt
          mountPath: /charts
      volumes:
      - name: chartmuseum-mnt
        hostPath:
          path: /etc/charts

---

apiVersion: v1
kind: Service
metadata:
  name: chartmuseum
spec:
  ports:
  - name: "port1"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: chartmuseum
  type: LoadBalancer