apiVersion: v1
kind: Pod
metadata:
  name: alice-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 6379
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"

